model: resources/bloom-1b7-finetuned-readme-270k-steps

prompt:
  separator: "&&&&&&"
  max_total_tokens: 1348
  max_source_code_tokens: 256

generation:
  do_sample: true
  max_length: 2048
  top_p: 0.92
  temperature: 0.95
